# Generated by Django 4.2.4 on 2023-08-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_compost_comcomments_cnt'),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompost',
            name='composts',
            field=models.ManyToManyField(blank=True, related_name='mycomposts', to='community.compost'),
        ),
    ]
