# Generated by Django 4.2.4 on 2023-08-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycom',
            name='comcomments',
        ),
        migrations.RemoveField(
            model_name='mycom',
            name='comreplies',
        ),
        migrations.RemoveField(
            model_name='mycom',
            name='maincomments',
        ),
        migrations.RemoveField(
            model_name='mycom',
            name='mainreplies',
        ),
        migrations.RemoveField(
            model_name='mycom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mycompost',
            name='composts',
        ),
        migrations.RemoveField(
            model_name='mycompost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myreport',
            name='mainposts',
        ),
        migrations.RemoveField(
            model_name='myreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myrequest',
            name='mainposts',
        ),
        migrations.RemoveField(
            model_name='myrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='MyCom',
        ),
        migrations.DeleteModel(
            name='MyComPost',
        ),
        migrations.DeleteModel(
            name='MyReport',
        ),
        migrations.DeleteModel(
            name='MyRequest',
        ),
    ]
