# Generated by Django 4.2.4 on 2023-08-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_community_image_community_media_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='community_media/'),
        ),
    ]
