# Generated by Django 4.2.4 on 2023-08-12 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_alter_community_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='compost_media/')),
            ],
        ),
        migrations.CreateModel(
            name='ComReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comreplies', to='community.comcomment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.AddField(
            model_name='comcomment',
            name='compost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comcomments', to='community.compost'),
        ),
        migrations.AddField(
            model_name='comcomment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityreaction',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.compost'),
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
