# Generated by Django 4.2.4 on 2023-08-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comcomment_compost_comreply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityreaction',
            old_name='community',
            new_name='compost',
        ),
    ]
