# Generated by Django 4.2.4 on 2023-08-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_rename_community_communityreaction_compost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comcomment',
            name='compost',
        ),
    ]
