# Generated by Django 4.2.4 on 2023-08-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_comcomment_compost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcomment',
            name='compost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comcomments', to='community.compost'),
        ),
    ]
