# Generated by Django 4.2.4 on 2023-08-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_compost_writer_alter_comreply_writer_compostmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compost',
            name='media',
        ),
        migrations.CreateModel(
            name='ComCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='comcomment_media/')),
                ('ComComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='community.comcomment')),
            ],
        ),
    ]
