# Generated by Django 4.2.4 on 2023-08-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_remove_compost_media_comcommentmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='compost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='compost_media/'),
        ),
    ]
