# Generated by Django 4.2.4 on 2023-08-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_alter_comcomment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comreply',
            name='comcomment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comcomment'),
        ),
    ]
