# Generated by Django 4.2.4 on 2023-08-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_second_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
