# Generated by Django 4.2.4 on 2023-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mainreply_maincomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='mainpost_media/'),
        ),
    ]
