# Generated by Django 4.2.4 on 2023-08-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainpost_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpost',
            name='media',
        ),
        migrations.CreateModel(
            name='MainPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='mainpost_media/')),
                ('mainpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainpost')),
            ],
        ),
    ]
