# Generated by Django 4.2.4 on 2023-08-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_mainpost_media_mainpostmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpostmedia',
            name='mainpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='main.mainpost'),
        ),
    ]
