# Generated by Django 4.2.4 on 2023-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mainpostmedia_mainpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='category',
            field=models.CharField(choices=[('a', 'Category A'), ('b', 'Category B'), ('c', 'Category C'), ('d', 'Category D')], max_length=1, null=True),
        ),
    ]
