# Generated by Django 4.2.4 on 2023-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpostmedia',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='mainpost_media/'),
        ),
    ]
