# Generated by Django 4.2.4 on 2023-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mainpostmedia_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpost',
            name='category',
        ),
        migrations.AlterField(
            model_name='mainpostmedia',
            name='media',
            field=models.FileField(null=True, upload_to='mainpost_media/'),
        ),
    ]
