# Generated by Django 4.2.4 on 2023-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_mainpost_category_alter_mainpostmedia_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpostmedia',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='mainpost_media/'),
        ),
    ]
