# Generated by Django 4.2.4 on 2023-08-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_mainpostmedia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='category',
            field=models.CharField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3'), (4, 'Category 4')], default='', max_length=10),
        ),
    ]
