# Generated by Django 4.2.4 on 2023-08-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mainpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='category',
            field=models.CharField(choices=[('교통사고', '교통사고'), ('도난,절도', '도난,절도'), ('실종신고', '실종신고'), ('기타', '기타')], default='', max_length=10),
        ),
    ]
