# Generated by Django 4.2.4 on 2023-08-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mainpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='maincomment_media/')),
                ('MainComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='main.maincomment')),
            ],
        ),
    ]
