# Generated by Django 4.2.4 on 2023-08-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_maincommentmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='jebo_bool',
            field=models.BooleanField(default=False),
        ),
    ]
