# Generated by Django 4.2.4 on 2023-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_mainpost_jebo_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpost',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
