# Generated by Django 4.2.4 on 2023-08-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mainpost_lat_mainpost_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
