# Generated by Django 4.2.4 on 2023-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_mainpost_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
