# Generated by Django 4.2.4 on 2023-08-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mainpost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='filmed_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
