# Generated by Django 4.2.4 on 2023-08-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_mainpost_filmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
