# Generated by Django 4.2.4 on 2023-08-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_mainpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
