# Generated by Django 4.2.4 on 2023-08-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_mainpost_created_at_alter_mainpost_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpostmedia',
            name='mainpost',
        ),
        migrations.AddField(
            model_name='maincomment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mainpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='MainCommentMedia',
        ),
        migrations.DeleteModel(
            name='MainPostMedia',
        ),
    ]
